### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Logarythms** [Rostlab/JS16_ProjectD_Group5#4]
- [x] Set up database (MongoDB)
- [ ] Connect Twitter-Rest client to DB
- [x] Connect Twitter-Streaming client to DB
- [ ] Run Sentiment Analysis for given data (1 week after episode airing for rest, 1h for streaming)
- [ ] Provide Visualization
